version: "3.9"

services:
  db:
    hostname: postgresdb
    image: postgres:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    hostname: django
    build: ./django-service
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    environment:
      - WAIT_FOR_SERVER=postgresdb
      - "WAIT_FOR_SERVER_PORT=${DATABASE_PORT:-5432}"
      - SKIP_STATIC_FILES=true
      - DO_DEV_CONFIGS=false
      - DO_DEV_INSTALLS=false
    expose:
      - 8000
    volumes:
      - ./django-service:/home/app/web
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - db
      - redis

  frontend:
    hostname: frontend
    build: ./frontend
    command: ./frontend-server.sh
    env_file:
      - dev.env
    expose:
      - 8080
    volumes:
      - ./frontend:/home/app/frontend
    depends_on:
      - db
      - web

  nginx:
    hostname: nginx
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - dev.env
    ports:
      - "80:80"
      - "20000:20000"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  staticfiles:
